FROM ultralytics/ultralytics:latest

WORKDIR /app

RUN pip install --no-cache-dir opencv-python-headless requests ultralytics

COPY . .

RUN mkdir -p /app/volumeFrame

EXPOSE 5001

CMD ["python", "detectionAndAlertSystem.py"]